services:
  client:
    environment:
      - FORCE_COLOR=1
    build: .
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./config.json
        target: /usr/src/app/config.json
      - type: bind
        source: ./plugins
        target: /usr/src/app/plugins
      - type: bind
        source: E:/Music/Plex (Not Tagged)/Various Artists/Downloads
        target: /usr/src/app/media/audio

      ###############################################
      # enable for plugins/plex_music_downloader.js #
      ###############################################
      # - type: bind                                #
      #   source: ~/downloads                       #
      #   target: /usr/src/app/media/audio          #
      ###############################################

# steps to deploy new build to server:
# https://stackoverflow.com/a/66539675
# $ docker compose pull
# $ docker compose up -d